var searchData=
[
  ['vcpkg_808',['Vcpkg',['../md_vcpkg_README_es.html',1,'']]],
  ['vcpkg_20and_20android_809',['Vcpkg and Android',['../md_vcpkg_docs_users_android.html',1,'']]],
  ['vcpkg_20and_20mingw_2dw64_810',['Vcpkg and Mingw-w64',['../md_vcpkg_docs_users_mingw.html',1,'']]],
  ['vcpkg_20install_811',['vcpkg install',['../md_vcpkg_docs_commands_install.html',1,'']]],
  ['vcpkg_20integrate_812',['vcpkg integrate',['../md_vcpkg_docs_commands_integrate.html',1,'']]],
  ['vcpkg_20pr_20checklist_813',['Vcpkg PR Checklist',['../md_vcpkg_docs_maintainers_pr_review_checklist.html',1,'']]],
  ['vcpkg_20remove_814',['vcpkg remove',['../md_vcpkg_docs_commands_remove.html',1,'']]],
  ['vcpkg_20search_815',['vcpkg search',['../md_vcpkg_docs_commands_search.html',1,'']]],
  ['vcpkg_20telemetry_20and_20privacy_816',['Vcpkg Telemetry and Privacy',['../md_vcpkg_docs_about_privacy.html',1,'']]],
  ['vcpkg_20x_2dupdate_2dbaseline_817',['vcpkg x-update-baseline',['../md_vcpkg_docs_commands_update_baseline.html',1,'']]],
  ['vcpkg_2dcmake_818',['vcpkg-cmake',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_819',['vcpkg-cmake-config',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_config.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_2emd_820',['vcpkg-cmake-config.md',['../vcpkg-cmake-config_8md.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_821',['vcpkg-cmake-get-vars',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_2emd_822',['vcpkg-cmake-get-vars.md',['../vcpkg-cmake-get-vars_8md.html',1,'']]],
  ['vcpkg_2dcmake_2emd_823',['vcpkg-cmake.md',['../vcpkg-cmake_8md.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_824',['vcpkg-get-python-packages',['../md_vcpkg_docs_maintainers_ports_vcpkg_get_python_packages.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_2emd_825',['vcpkg-get-python-packages.md',['../vcpkg-get-python-packages_8md.html',1,'']]],
  ['vcpkg_2dgn_826',['vcpkg-gn',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn.html',1,'']]],
  ['vcpkg_2dgn_2emd_827',['vcpkg-gn.md',['../vcpkg-gn_8md.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_828',['vcpkg-pkgconfig-get-modules',['../md_vcpkg_docs_maintainers_ports_vcpkg_pkgconfig_get_modules.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_2emd_829',['vcpkg-pkgconfig-get-modules.md',['../vcpkg-pkgconfig-get-modules_8md.html',1,'']]],
  ['vcpkg_2dqmake_830',['vcpkg-qmake',['../md_vcpkg_docs_maintainers_ports_vcpkg_qmake.html',1,'']]],
  ['vcpkg_2dqmake_2emd_831',['vcpkg-qmake.md',['../vcpkg-qmake_8md.html',1,'']]],
  ['vcpkg_3a_20export_20android_20prefab_20archives_20_28aar_20files_29_832',['Vcpkg: export Android prefab Archives (AAR files)',['../md_vcpkg_docs_specifications_prefab.html',1,'']]],
  ['vcpkg_3a_20vue_20d_27ensemble_833',['Vcpkg: Vue d&apos;ensemble',['../md_vcpkg_README_fr.html',1,'']]],
  ['vcpkg_3a_20总览_834',['Vcpkg: 总览',['../md_vcpkg_README_zh_CN.html',1,'']]],
  ['vcpkg_3a_20개요_835',['Vcpkg: 개요',['../md_vcpkg_README_ko_KR.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_836',['vcpkg_acquire_msys',['../md_vcpkg_docs_maintainers_vcpkg_acquire_msys.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_2emd_837',['vcpkg_acquire_msys.md',['../vcpkg__acquire__msys_8md.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_838',['vcpkg_add_to_path',['../md_vcpkg_docs_maintainers_vcpkg_add_to_path.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_2emd_839',['vcpkg_add_to_path.md',['../vcpkg__add__to__path_8md.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_840',['vcpkg_apply_patches',['../md_vcpkg_docs_maintainers_vcpkg_apply_patches.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_2emd_841',['vcpkg_apply_patches.md',['../vcpkg__apply__patches_8md.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_842',['vcpkg_backup_restore_env_vars',['../md_vcpkg_docs_maintainers_vcpkg_backup_restore_env_vars.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_2emd_843',['vcpkg_backup_restore_env_vars.md',['../vcpkg__backup__restore__env__vars_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_844',['vcpkg_build_cmake',['../md_vcpkg_docs_maintainers_vcpkg_build_cmake.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_2emd_845',['vcpkg_build_cmake.md',['../vcpkg__build__cmake_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_846',['vcpkg_build_make',['../md_vcpkg_docs_maintainers_vcpkg_build_make.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_2emd_847',['vcpkg_build_make.md',['../vcpkg__build__make_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_848',['vcpkg_build_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_build_msbuild.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_2emd_849',['vcpkg_build_msbuild.md',['../vcpkg__build__msbuild_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_850',['vcpkg_build_ninja',['../md_vcpkg_docs_maintainers_vcpkg_build_ninja.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_2emd_851',['vcpkg_build_ninja.md',['../vcpkg__build__ninja_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_852',['vcpkg_build_nmake',['../md_vcpkg_docs_maintainers_vcpkg_build_nmake.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_2emd_853',['vcpkg_build_nmake.md',['../vcpkg__build__nmake_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_854',['vcpkg_build_qmake',['../md_vcpkg_docs_maintainers_vcpkg_build_qmake.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_2emd_855',['vcpkg_build_qmake.md',['../vcpkg__build__qmake_8md.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_856',['vcpkg_buildpath_length_warning',['../md_vcpkg_docs_maintainers_vcpkg_buildpath_length_warning.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_2emd_857',['vcpkg_buildpath_length_warning.md',['../vcpkg__buildpath__length__warning_8md.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_858',['vcpkg_catalog_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_catalog_release_process.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_2emd_859',['vcpkg_catalog_release_process.md',['../vcpkg__catalog__release__process_8md.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_860',['vcpkg_check_features',['../md_vcpkg_docs_maintainers_vcpkg_check_features.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_2emd_861',['vcpkg_check_features.md',['../vcpkg__check__features_8md.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_862',['vcpkg_check_linkage',['../md_vcpkg_docs_maintainers_vcpkg_check_linkage.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_2emd_863',['vcpkg_check_linkage.md',['../vcpkg__check__linkage_8md.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_864',['vcpkg_clean_executables_in_bin',['../md_vcpkg_docs_maintainers_vcpkg_clean_executables_in_bin.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_2emd_865',['vcpkg_clean_executables_in_bin.md',['../vcpkg__clean__executables__in__bin_8md.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_866',['vcpkg_clean_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_clean_msbuild.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_2emd_867',['vcpkg_clean_msbuild.md',['../vcpkg__clean__msbuild_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_868',['vcpkg_cmake_build',['../md_vcpkg_docs_maintainers_vcpkg_cmake_build.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_2emd_869',['vcpkg_cmake_build.md',['../vcpkg__cmake__build_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_870',['vcpkg_cmake_config_fixup',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_config_vcpkg_cmake_config_fixup.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_2emd_871',['vcpkg_cmake_config_fixup.md',['../vcpkg__cmake__config__fixup_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_872',['vcpkg_cmake_configure',['../md_vcpkg_docs_maintainers_vcpkg_cmake_configure.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_2emd_873',['vcpkg_cmake_configure.md',['../vcpkg__cmake__configure_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_874',['vcpkg_cmake_get_vars',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_2emd_875',['vcpkg_cmake_get_vars.md',['../vcpkg__cmake__get__vars_8md.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_876',['vcpkg_cmake_install',['../md_vcpkg_docs_maintainers_vcpkg_cmake_install.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_2emd_877',['vcpkg_cmake_install.md',['../vcpkg__cmake__install_8md.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_878',['vcpkg_common_definitions',['../md_vcpkg_docs_maintainers_vcpkg_common_definitions.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_2emd_879',['vcpkg_common_definitions.md',['../vcpkg__common__definitions_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_880',['vcpkg_configure_cmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_cmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_2emd_881',['vcpkg_configure_cmake.md',['../vcpkg__configure__cmake_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_882',['vcpkg_configure_gn',['../md_vcpkg_docs_maintainers_vcpkg_configure_gn.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_2emd_883',['vcpkg_configure_gn.md',['../vcpkg__configure__gn_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_884',['vcpkg_configure_make',['../md_vcpkg_docs_maintainers_vcpkg_configure_make.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_2emd_885',['vcpkg_configure_make.md',['../vcpkg__configure__make_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_886',['vcpkg_configure_meson',['../md_vcpkg_docs_maintainers_vcpkg_configure_meson.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_2emd_887',['vcpkg_configure_meson.md',['../vcpkg__configure__meson_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_888',['vcpkg_configure_qmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_qmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_2emd_889',['vcpkg_configure_qmake.md',['../vcpkg__configure__qmake_8md.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_890',['vcpkg_copy_pdbs',['../md_vcpkg_docs_maintainers_vcpkg_copy_pdbs.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_2emd_891',['vcpkg_copy_pdbs.md',['../vcpkg__copy__pdbs_8md.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_892',['vcpkg_copy_tool_dependencies',['../md_vcpkg_docs_maintainers_vcpkg_copy_tool_dependencies.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_2emd_893',['vcpkg_copy_tool_dependencies.md',['../vcpkg__copy__tool__dependencies_8md.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_894',['vcpkg_copy_tools',['../md_vcpkg_docs_maintainers_vcpkg_copy_tools.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_2emd_895',['vcpkg_copy_tools.md',['../vcpkg__copy__tools_8md.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_896',['vcpkg_download_distfile',['../md_vcpkg_docs_maintainers_vcpkg_download_distfile.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_2emd_897',['vcpkg_download_distfile.md',['../vcpkg__download__distfile_8md.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_898',['vcpkg_execute_build_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_build_process.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_2emd_899',['vcpkg_execute_build_process.md',['../vcpkg__execute__build__process_8md.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_900',['vcpkg_execute_in_download_mode',['../md_vcpkg_docs_maintainers_vcpkg_execute_in_download_mode.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_2emd_901',['vcpkg_execute_in_download_mode.md',['../vcpkg__execute__in__download__mode_8md.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_902',['vcpkg_execute_required_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_2emd_903',['vcpkg_execute_required_process.md',['../vcpkg__execute__required__process_8md.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_904',['vcpkg_execute_required_process_repeat',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process_repeat.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_2emd_905',['vcpkg_execute_required_process_repeat.md',['../vcpkg__execute__required__process__repeat_8md.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_906',['vcpkg_extract_source_archive',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_2emd_907',['vcpkg_extract_source_archive.md',['../vcpkg__extract__source__archive_8md.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_908',['vcpkg_extract_source_archive_ex',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive_ex.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_2emd_909',['vcpkg_extract_source_archive_ex.md',['../vcpkg__extract__source__archive__ex_8md.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_910',['vcpkg_fail_port_install',['../md_vcpkg_docs_maintainers_vcpkg_fail_port_install.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_2emd_911',['vcpkg_fail_port_install.md',['../vcpkg__fail__port__install_8md.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_912',['vcpkg_find_acquire_program',['../md_vcpkg_docs_maintainers_vcpkg_find_acquire_program.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_2emd_913',['vcpkg_find_acquire_program.md',['../vcpkg__find__acquire__program_8md.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_914',['vcpkg_find_fortran',['../md_vcpkg_docs_maintainers_vcpkg_find_fortran.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_2emd_915',['vcpkg_find_fortran.md',['../vcpkg__find__fortran_8md.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_916',['vcpkg_fixup_cmake_targets',['../md_vcpkg_docs_maintainers_vcpkg_fixup_cmake_targets.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_2emd_917',['vcpkg_fixup_cmake_targets.md',['../vcpkg__fixup__cmake__targets_8md.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_918',['vcpkg_fixup_pkgconfig',['../md_vcpkg_docs_maintainers_vcpkg_fixup_pkgconfig.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_2emd_919',['vcpkg_fixup_pkgconfig.md',['../vcpkg__fixup__pkgconfig_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_920',['vcpkg_from_bitbucket',['../md_vcpkg_docs_maintainers_vcpkg_from_bitbucket.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_2emd_921',['vcpkg_from_bitbucket.md',['../vcpkg__from__bitbucket_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_922',['vcpkg_from_git',['../md_vcpkg_docs_maintainers_vcpkg_from_git.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_2emd_923',['vcpkg_from_git.md',['../vcpkg__from__git_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_924',['vcpkg_from_github',['../md_vcpkg_docs_maintainers_vcpkg_from_github.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_2emd_925',['vcpkg_from_github.md',['../vcpkg__from__github_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_926',['vcpkg_from_gitlab',['../md_vcpkg_docs_maintainers_vcpkg_from_gitlab.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_2emd_927',['vcpkg_from_gitlab.md',['../vcpkg__from__gitlab_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_928',['vcpkg_from_sourceforge',['../md_vcpkg_docs_maintainers_vcpkg_from_sourceforge.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_2emd_929',['vcpkg_from_sourceforge.md',['../vcpkg__from__sourceforge_8md.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_930',['vcpkg_get_program_files_platform_bitness',['../md_vcpkg_docs_maintainers_vcpkg_get_program_files_platform_bitness.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_2emd_931',['vcpkg_get_program_files_platform_bitness.md',['../vcpkg__get__program__files__platform__bitness_8md.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_932',['vcpkg_get_windows_sdk',['../md_vcpkg_docs_maintainers_vcpkg_get_windows_sdk.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_2emd_933',['vcpkg_get_windows_sdk.md',['../vcpkg__get__windows__sdk_8md.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_934',['vcpkg_gn_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_configure.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_2emd_935',['vcpkg_gn_configure.md',['../vcpkg__gn__configure_8md.html',1,'']]],
  ['vcpkg_5fgn_5finstall_936',['vcpkg_gn_install',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_install.html',1,'']]],
  ['vcpkg_5fgn_5finstall_2emd_937',['vcpkg_gn_install.md',['../vcpkg__gn__install_8md.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_938',['vcpkg_host_path_list',['../md_vcpkg_docs_maintainers_vcpkg_host_path_list.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_2emd_939',['vcpkg_host_path_list.md',['../vcpkg__host__path__list_8md.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_940',['vcpkg_install_cmake',['../md_vcpkg_docs_maintainers_vcpkg_install_cmake.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_2emd_941',['vcpkg_install_cmake.md',['../vcpkg__install__cmake_8md.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_942',['vcpkg_install_copyright',['../md_vcpkg_docs_maintainers_vcpkg_install_copyright.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_2emd_943',['vcpkg_install_copyright.md',['../vcpkg__install__copyright_8md.html',1,'']]],
  ['vcpkg_5finstall_5fgn_944',['vcpkg_install_gn',['../md_vcpkg_docs_maintainers_vcpkg_install_gn.html',1,'']]],
  ['vcpkg_5finstall_5fgn_2emd_945',['vcpkg_install_gn.md',['../vcpkg__install__gn_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmake_946',['vcpkg_install_make',['../md_vcpkg_docs_maintainers_vcpkg_install_make.html',1,'']]],
  ['vcpkg_5finstall_5fmake_2emd_947',['vcpkg_install_make.md',['../vcpkg__install__make_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_948',['vcpkg_install_meson',['../md_vcpkg_docs_maintainers_vcpkg_install_meson.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_2emd_949',['vcpkg_install_meson.md',['../vcpkg__install__meson_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_950',['vcpkg_install_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_install_msbuild.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_2emd_951',['vcpkg_install_msbuild.md',['../vcpkg__install__msbuild_8md.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_952',['vcpkg_install_nmake',['../md_vcpkg_docs_maintainers_vcpkg_install_nmake.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_2emd_953',['vcpkg_install_nmake.md',['../vcpkg__install__nmake_8md.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_954',['vcpkg_install_qmake',['../md_vcpkg_docs_maintainers_vcpkg_install_qmake.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_2emd_955',['vcpkg_install_qmake.md',['../vcpkg__install__qmake_8md.html',1,'']]],
  ['vcpkg_5flist_956',['vcpkg_list',['../md_vcpkg_docs_maintainers_vcpkg_list.html',1,'']]],
  ['vcpkg_5flist_2emd_957',['vcpkg_list.md',['../vcpkg__list_8md.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_958',['vcpkg_minimum_required',['../md_vcpkg_docs_maintainers_vcpkg_minimum_required.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_2emd_959',['vcpkg_minimum_required.md',['../vcpkg__minimum__required_8md.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_960',['vcpkg_qmake_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_configure.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_2emd_961',['vcpkg_qmake_configure.md',['../vcpkg__qmake__configure_8md.html',1,'']]],
  ['vcpkg_5freplace_5fstring_962',['vcpkg_replace_string',['../md_vcpkg_docs_maintainers_vcpkg_replace_string.html',1,'']]],
  ['vcpkg_5freplace_5fstring_2emd_963',['vcpkg_replace_string.md',['../vcpkg__replace__string_8md.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_964',['vcpkg_tool_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_tool_release_process.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_2emd_965',['vcpkg_tool_release_process.md',['../vcpkg__tool__release__process_8md.html',1,'']]],
  ['version_966',['VERSION',['../fficonfig_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;fficonfig.h'],['../libidn2_2config_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;config.h'],['../ragel_2config_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;config.h']]],
  ['version_967',['version',['../namespaceconvert__lib__params__linux.html#a2e27b49038043d8367cd4509c7740b13',1,'convert_lib_params_linux.version()'],['../namespaceconvert__lib__params__macos.html#aa68c10847a16ba23f9aef1fffef13103',1,'convert_lib_params_macos.version()'],['../namespacegenerate__static__link__cmd__linux.html#a0d0804d60b7bf85cdabd5552dd5d0964',1,'generate_static_link_cmd_linux.version()'],['../namespacegenerate__static__link__cmd__macos.html#a4bb029e41c672ec5e3fd22b7612cf9f1',1,'generate_static_link_cmd_macos.version()'],['../namespacegenerate__static__link__cmd__windows.html#a1da18c6c98aac4b8f0b2e7b07bfa7596',1,'generate_static_link_cmd_windows.version()']]],
  ['versioning_968',['Versioning',['../md_vcpkg_docs_users_versioning.html',1,'']]],
  ['versioning_20specification_969',['Versioning Specification',['../md_vcpkg_docs_specifications_versioning.html',1,'']]],
  ['versioning_2egetting_2dstarted_2emd_970',['versioning.getting-started.md',['../versioning_8getting-started_8md.html',1,'']]],
  ['versioning_2eimplementation_2ddetails_2emd_971',['versioning.implementation-details.md',['../versioning_8implementation-details_8md.html',1,'']]],
  ['versioning_2emd_972',['versioning.md',['../users_2versioning_8md.html',1,'(Global Namespace)'],['../specifications_2versioning_8md.html',1,'(Global Namespace)']]],
  ['versioning_3a_20implementation_20details_973',['Versioning: Implementation details',['../md_vcpkg_docs_users_versioning_implementation_details.html',1,'']]],
  ['versions_5fdb_5fdirectory_974',['VERSIONS_DB_DIRECTORY',['../namespacegeneratePortVersionsDb.html#a54130cc174e3bf89fd87aff1453ceea8',1,'generatePortVersionsDb.VERSIONS_DB_DIRECTORY()'],['../namespacegenerateBaseline.html#a5437458e3e74922a210b4f7d39e20ef0',1,'generateBaseline.VERSIONS_DB_DIRECTORY()']]],
  ['void_5fsighandler_975',['VOID_SIGHANDLER',['../readline-win32_2config_8h.html#ae8a37fa6c27ec6bf124faa70fcd848c5',1,'VOID_SIGHANDLER():&#160;config.h'],['../readline-win32_2config_8h.html#ae8a37fa6c27ec6bf124faa70fcd848c5',1,'VOID_SIGHANDLER():&#160;config.h']]]
];
