var searchData=
[
  ['vcpkg_20telemetry_20and_20privacy_708',['Vcpkg Telemetry and Privacy',['../md_vcpkg_docs_about_privacy.html',1,'']]],
  ['vcpkg_20install_709',['vcpkg install',['../md_vcpkg_docs_commands_install.html',1,'']]],
  ['vcpkg_20integrate_710',['vcpkg integrate',['../md_vcpkg_docs_commands_integrate.html',1,'']]],
  ['vcpkg_20remove_711',['vcpkg remove',['../md_vcpkg_docs_commands_remove.html',1,'']]],
  ['vcpkg_20search_712',['vcpkg search',['../md_vcpkg_docs_commands_search.html',1,'']]],
  ['vcpkg_20x_2dupdate_2dbaseline_713',['vcpkg x-update-baseline',['../md_vcpkg_docs_commands_update-baseline.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_714',['vcpkg_catalog_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_catalog_release_process.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_715',['vcpkg_tool_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_tool_release_process.html',1,'']]],
  ['vcpkg_2dcmake_716',['vcpkg-cmake',['../md_vcpkg_docs_maintainers_ports_vcpkg-cmake.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_717',['vcpkg-cmake-config',['../md_vcpkg_docs_maintainers_ports_vcpkg-cmake-config.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_718',['vcpkg_cmake_config_fixup',['../md_vcpkg_docs_maintainers_ports_vcpkg-cmake-config_vcpkg_cmake_config_fixup.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_719',['vcpkg-cmake-get-vars',['../md_vcpkg_docs_maintainers_ports_vcpkg-cmake-get-vars.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_720',['vcpkg_cmake_get_vars',['../md_vcpkg_docs_maintainers_ports_vcpkg-cmake-get-vars_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_721',['vcpkg-get-python-packages',['../md_vcpkg_docs_maintainers_ports_vcpkg-get-python-packages.html',1,'']]],
  ['vcpkg_2dgn_722',['vcpkg-gn',['../md_vcpkg_docs_maintainers_ports_vcpkg-gn.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_723',['vcpkg_gn_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg-gn_vcpkg_gn_configure.html',1,'']]],
  ['vcpkg_5fgn_5finstall_724',['vcpkg_gn_install',['../md_vcpkg_docs_maintainers_ports_vcpkg-gn_vcpkg_gn_install.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_725',['vcpkg-pkgconfig-get-modules',['../md_vcpkg_docs_maintainers_ports_vcpkg-pkgconfig-get-modules.html',1,'']]],
  ['vcpkg_2dqmake_726',['vcpkg-qmake',['../md_vcpkg_docs_maintainers_ports_vcpkg-qmake.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_727',['vcpkg_qmake_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg-qmake_vcpkg_qmake_configure.html',1,'']]],
  ['vcpkg_20pr_20checklist_728',['Vcpkg PR Checklist',['../md_vcpkg_docs_maintainers_pr-review-checklist.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_729',['vcpkg_acquire_msys',['../md_vcpkg_docs_maintainers_vcpkg_acquire_msys.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_730',['vcpkg_add_to_path',['../md_vcpkg_docs_maintainers_vcpkg_add_to_path.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_731',['vcpkg_apply_patches',['../md_vcpkg_docs_maintainers_vcpkg_apply_patches.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_732',['vcpkg_backup_restore_env_vars',['../md_vcpkg_docs_maintainers_vcpkg_backup_restore_env_vars.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_733',['vcpkg_build_cmake',['../md_vcpkg_docs_maintainers_vcpkg_build_cmake.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_734',['vcpkg_build_make',['../md_vcpkg_docs_maintainers_vcpkg_build_make.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_735',['vcpkg_build_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_build_msbuild.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_736',['vcpkg_build_ninja',['../md_vcpkg_docs_maintainers_vcpkg_build_ninja.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_737',['vcpkg_build_nmake',['../md_vcpkg_docs_maintainers_vcpkg_build_nmake.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_738',['vcpkg_build_qmake',['../md_vcpkg_docs_maintainers_vcpkg_build_qmake.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_739',['vcpkg_buildpath_length_warning',['../md_vcpkg_docs_maintainers_vcpkg_buildpath_length_warning.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_740',['vcpkg_check_features',['../md_vcpkg_docs_maintainers_vcpkg_check_features.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_741',['vcpkg_check_linkage',['../md_vcpkg_docs_maintainers_vcpkg_check_linkage.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_742',['vcpkg_clean_executables_in_bin',['../md_vcpkg_docs_maintainers_vcpkg_clean_executables_in_bin.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_743',['vcpkg_clean_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_clean_msbuild.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_744',['vcpkg_cmake_build',['../md_vcpkg_docs_maintainers_vcpkg_cmake_build.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_745',['vcpkg_cmake_configure',['../md_vcpkg_docs_maintainers_vcpkg_cmake_configure.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_746',['vcpkg_cmake_install',['../md_vcpkg_docs_maintainers_vcpkg_cmake_install.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_747',['vcpkg_common_definitions',['../md_vcpkg_docs_maintainers_vcpkg_common_definitions.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_748',['vcpkg_configure_cmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_cmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_749',['vcpkg_configure_gn',['../md_vcpkg_docs_maintainers_vcpkg_configure_gn.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_750',['vcpkg_configure_make',['../md_vcpkg_docs_maintainers_vcpkg_configure_make.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_751',['vcpkg_configure_meson',['../md_vcpkg_docs_maintainers_vcpkg_configure_meson.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_752',['vcpkg_configure_qmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_qmake.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_753',['vcpkg_copy_pdbs',['../md_vcpkg_docs_maintainers_vcpkg_copy_pdbs.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_754',['vcpkg_copy_tool_dependencies',['../md_vcpkg_docs_maintainers_vcpkg_copy_tool_dependencies.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_755',['vcpkg_copy_tools',['../md_vcpkg_docs_maintainers_vcpkg_copy_tools.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_756',['vcpkg_download_distfile',['../md_vcpkg_docs_maintainers_vcpkg_download_distfile.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_757',['vcpkg_execute_build_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_build_process.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_758',['vcpkg_execute_in_download_mode',['../md_vcpkg_docs_maintainers_vcpkg_execute_in_download_mode.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_759',['vcpkg_execute_required_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_760',['vcpkg_execute_required_process_repeat',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process_repeat.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_761',['vcpkg_extract_source_archive',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_762',['vcpkg_extract_source_archive_ex',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive_ex.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_763',['vcpkg_fail_port_install',['../md_vcpkg_docs_maintainers_vcpkg_fail_port_install.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_764',['vcpkg_find_acquire_program',['../md_vcpkg_docs_maintainers_vcpkg_find_acquire_program.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_765',['vcpkg_find_fortran',['../md_vcpkg_docs_maintainers_vcpkg_find_fortran.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_766',['vcpkg_fixup_cmake_targets',['../md_vcpkg_docs_maintainers_vcpkg_fixup_cmake_targets.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_767',['vcpkg_fixup_pkgconfig',['../md_vcpkg_docs_maintainers_vcpkg_fixup_pkgconfig.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_768',['vcpkg_from_bitbucket',['../md_vcpkg_docs_maintainers_vcpkg_from_bitbucket.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_769',['vcpkg_from_git',['../md_vcpkg_docs_maintainers_vcpkg_from_git.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_770',['vcpkg_from_github',['../md_vcpkg_docs_maintainers_vcpkg_from_github.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_771',['vcpkg_from_gitlab',['../md_vcpkg_docs_maintainers_vcpkg_from_gitlab.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_772',['vcpkg_from_sourceforge',['../md_vcpkg_docs_maintainers_vcpkg_from_sourceforge.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_773',['vcpkg_get_program_files_platform_bitness',['../md_vcpkg_docs_maintainers_vcpkg_get_program_files_platform_bitness.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_774',['vcpkg_get_windows_sdk',['../md_vcpkg_docs_maintainers_vcpkg_get_windows_sdk.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_775',['vcpkg_host_path_list',['../md_vcpkg_docs_maintainers_vcpkg_host_path_list.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_776',['vcpkg_install_cmake',['../md_vcpkg_docs_maintainers_vcpkg_install_cmake.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_777',['vcpkg_install_copyright',['../md_vcpkg_docs_maintainers_vcpkg_install_copyright.html',1,'']]],
  ['vcpkg_5finstall_5fgn_778',['vcpkg_install_gn',['../md_vcpkg_docs_maintainers_vcpkg_install_gn.html',1,'']]],
  ['vcpkg_5finstall_5fmake_779',['vcpkg_install_make',['../md_vcpkg_docs_maintainers_vcpkg_install_make.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_780',['vcpkg_install_meson',['../md_vcpkg_docs_maintainers_vcpkg_install_meson.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_781',['vcpkg_install_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_install_msbuild.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_782',['vcpkg_install_nmake',['../md_vcpkg_docs_maintainers_vcpkg_install_nmake.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_783',['vcpkg_install_qmake',['../md_vcpkg_docs_maintainers_vcpkg_install_qmake.html',1,'']]],
  ['vcpkg_5flist_784',['vcpkg_list',['../md_vcpkg_docs_maintainers_vcpkg_list.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_785',['vcpkg_minimum_required',['../md_vcpkg_docs_maintainers_vcpkg_minimum_required.html',1,'']]],
  ['vcpkg_5freplace_5fstring_786',['vcpkg_replace_string',['../md_vcpkg_docs_maintainers_vcpkg_replace_string.html',1,'']]],
  ['vcpkg_3a_20export_20android_20prefab_20archives_20_28aar_20files_29_787',['Vcpkg: export Android prefab Archives (AAR files)',['../md_vcpkg_docs_specifications_prefab.html',1,'']]],
  ['versioning_20specification_788',['Versioning Specification',['../md_vcpkg_docs_specifications_versioning.html',1,'']]],
  ['vcpkg_20and_20android_789',['Vcpkg and Android',['../md_vcpkg_docs_users_android.html',1,'']]],
  ['vcpkg_20and_20mingw_2dw64_790',['Vcpkg and Mingw-w64',['../md_vcpkg_docs_users_mingw.html',1,'']]],
  ['versioning_791',['Versioning',['../md_vcpkg_docs_users_versioning.html',1,'']]],
  ['versioning_3a_20implementation_20details_792',['Versioning: Implementation details',['../md_vcpkg_docs_users_versioning_8implementation-details.html',1,'']]],
  ['vcpkg_793',['Vcpkg',['../md_vcpkg_README_es.html',1,'']]],
  ['vcpkg_3a_20vue_20d_27ensemble_794',['Vcpkg: Vue d&apos;ensemble',['../md_vcpkg_README_fr.html',1,'']]],
  ['vcpkg_3a_20개요_795',['Vcpkg: 개요',['../md_vcpkg_README_ko_KR.html',1,'']]],
  ['vcpkg_3a_20总览_796',['Vcpkg: 总览',['../md_vcpkg_README_zh_CN.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_2emd_797',['vcpkg-cmake-config.md',['../vcpkg-cmake-config_8md.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_2emd_798',['vcpkg-cmake-get-vars.md',['../vcpkg-cmake-get-vars_8md.html',1,'']]],
  ['vcpkg_2dcmake_2emd_799',['vcpkg-cmake.md',['../vcpkg-cmake_8md.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_2emd_800',['vcpkg-get-python-packages.md',['../vcpkg-get-python-packages_8md.html',1,'']]],
  ['vcpkg_2dgn_2emd_801',['vcpkg-gn.md',['../vcpkg-gn_8md.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_2emd_802',['vcpkg-pkgconfig-get-modules.md',['../vcpkg-pkgconfig-get-modules_8md.html',1,'']]],
  ['vcpkg_2dqmake_2emd_803',['vcpkg-qmake.md',['../vcpkg-qmake_8md.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_2emd_804',['vcpkg_acquire_msys.md',['../vcpkg__acquire__msys_8md.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_2emd_805',['vcpkg_add_to_path.md',['../vcpkg__add__to__path_8md.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_2emd_806',['vcpkg_apply_patches.md',['../vcpkg__apply__patches_8md.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_2emd_807',['vcpkg_backup_restore_env_vars.md',['../vcpkg__backup__restore__env__vars_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_2emd_808',['vcpkg_build_cmake.md',['../vcpkg__build__cmake_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_2emd_809',['vcpkg_build_make.md',['../vcpkg__build__make_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_2emd_810',['vcpkg_build_msbuild.md',['../vcpkg__build__msbuild_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_2emd_811',['vcpkg_build_ninja.md',['../vcpkg__build__ninja_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_2emd_812',['vcpkg_build_nmake.md',['../vcpkg__build__nmake_8md.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_2emd_813',['vcpkg_build_qmake.md',['../vcpkg__build__qmake_8md.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_2emd_814',['vcpkg_buildpath_length_warning.md',['../vcpkg__buildpath__length__warning_8md.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_2emd_815',['vcpkg_catalog_release_process.md',['../vcpkg__catalog__release__process_8md.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_2emd_816',['vcpkg_check_features.md',['../vcpkg__check__features_8md.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_2emd_817',['vcpkg_check_linkage.md',['../vcpkg__check__linkage_8md.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_2emd_818',['vcpkg_clean_executables_in_bin.md',['../vcpkg__clean__executables__in__bin_8md.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_2emd_819',['vcpkg_clean_msbuild.md',['../vcpkg__clean__msbuild_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_2emd_820',['vcpkg_cmake_build.md',['../vcpkg__cmake__build_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_2emd_821',['vcpkg_cmake_config_fixup.md',['../vcpkg__cmake__config__fixup_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_2emd_822',['vcpkg_cmake_configure.md',['../vcpkg__cmake__configure_8md.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_2emd_823',['vcpkg_cmake_get_vars.md',['../vcpkg__cmake__get__vars_8md.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_2emd_824',['vcpkg_cmake_install.md',['../vcpkg__cmake__install_8md.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_2emd_825',['vcpkg_common_definitions.md',['../vcpkg__common__definitions_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_2emd_826',['vcpkg_configure_cmake.md',['../vcpkg__configure__cmake_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_2emd_827',['vcpkg_configure_gn.md',['../vcpkg__configure__gn_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_2emd_828',['vcpkg_configure_make.md',['../vcpkg__configure__make_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_2emd_829',['vcpkg_configure_meson.md',['../vcpkg__configure__meson_8md.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_2emd_830',['vcpkg_configure_qmake.md',['../vcpkg__configure__qmake_8md.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_2emd_831',['vcpkg_copy_pdbs.md',['../vcpkg__copy__pdbs_8md.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_2emd_832',['vcpkg_copy_tool_dependencies.md',['../vcpkg__copy__tool__dependencies_8md.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_2emd_833',['vcpkg_copy_tools.md',['../vcpkg__copy__tools_8md.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_2emd_834',['vcpkg_download_distfile.md',['../vcpkg__download__distfile_8md.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_2emd_835',['vcpkg_execute_build_process.md',['../vcpkg__execute__build__process_8md.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_2emd_836',['vcpkg_execute_in_download_mode.md',['../vcpkg__execute__in__download__mode_8md.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_2emd_837',['vcpkg_execute_required_process.md',['../vcpkg__execute__required__process_8md.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_2emd_838',['vcpkg_execute_required_process_repeat.md',['../vcpkg__execute__required__process__repeat_8md.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_2emd_839',['vcpkg_extract_source_archive.md',['../vcpkg__extract__source__archive_8md.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_2emd_840',['vcpkg_extract_source_archive_ex.md',['../vcpkg__extract__source__archive__ex_8md.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_2emd_841',['vcpkg_fail_port_install.md',['../vcpkg__fail__port__install_8md.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_2emd_842',['vcpkg_find_acquire_program.md',['../vcpkg__find__acquire__program_8md.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_2emd_843',['vcpkg_find_fortran.md',['../vcpkg__find__fortran_8md.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_2emd_844',['vcpkg_fixup_cmake_targets.md',['../vcpkg__fixup__cmake__targets_8md.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_2emd_845',['vcpkg_fixup_pkgconfig.md',['../vcpkg__fixup__pkgconfig_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_2emd_846',['vcpkg_from_bitbucket.md',['../vcpkg__from__bitbucket_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_2emd_847',['vcpkg_from_git.md',['../vcpkg__from__git_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_2emd_848',['vcpkg_from_github.md',['../vcpkg__from__github_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_2emd_849',['vcpkg_from_gitlab.md',['../vcpkg__from__gitlab_8md.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_2emd_850',['vcpkg_from_sourceforge.md',['../vcpkg__from__sourceforge_8md.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_2emd_851',['vcpkg_get_program_files_platform_bitness.md',['../vcpkg__get__program__files__platform__bitness_8md.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_2emd_852',['vcpkg_get_windows_sdk.md',['../vcpkg__get__windows__sdk_8md.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_2emd_853',['vcpkg_gn_configure.md',['../vcpkg__gn__configure_8md.html',1,'']]],
  ['vcpkg_5fgn_5finstall_2emd_854',['vcpkg_gn_install.md',['../vcpkg__gn__install_8md.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_2emd_855',['vcpkg_host_path_list.md',['../vcpkg__host__path__list_8md.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_2emd_856',['vcpkg_install_cmake.md',['../vcpkg__install__cmake_8md.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_2emd_857',['vcpkg_install_copyright.md',['../vcpkg__install__copyright_8md.html',1,'']]],
  ['vcpkg_5finstall_5fgn_2emd_858',['vcpkg_install_gn.md',['../vcpkg__install__gn_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmake_2emd_859',['vcpkg_install_make.md',['../vcpkg__install__make_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_2emd_860',['vcpkg_install_meson.md',['../vcpkg__install__meson_8md.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_2emd_861',['vcpkg_install_msbuild.md',['../vcpkg__install__msbuild_8md.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_2emd_862',['vcpkg_install_nmake.md',['../vcpkg__install__nmake_8md.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_2emd_863',['vcpkg_install_qmake.md',['../vcpkg__install__qmake_8md.html',1,'']]],
  ['vcpkg_5flist_2emd_864',['vcpkg_list.md',['../vcpkg__list_8md.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_2emd_865',['vcpkg_minimum_required.md',['../vcpkg__minimum__required_8md.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_2emd_866',['vcpkg_qmake_configure.md',['../vcpkg__qmake__configure_8md.html',1,'']]],
  ['vcpkg_5freplace_5fstring_2emd_867',['vcpkg_replace_string.md',['../vcpkg__replace__string_8md.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_2emd_868',['vcpkg_tool_release_process.md',['../vcpkg__tool__release__process_8md.html',1,'']]],
  ['version_869',['version',['../namespaceconvert__lib__params__linux.html#a2e27b49038043d8367cd4509c7740b13',1,'convert_lib_params_linux.version()'],['../namespaceconvert__lib__params__macos.html#aa68c10847a16ba23f9aef1fffef13103',1,'convert_lib_params_macos.version()'],['../namespacegenerate__static__link__cmd__linux.html#a0d0804d60b7bf85cdabd5552dd5d0964',1,'generate_static_link_cmd_linux.version()'],['../namespacegenerate__static__link__cmd__macos.html#a4bb029e41c672ec5e3fd22b7612cf9f1',1,'generate_static_link_cmd_macos.version()'],['../namespacegenerate__static__link__cmd__windows.html#a1da18c6c98aac4b8f0b2e7b07bfa7596',1,'generate_static_link_cmd_windows.version()'],['../fficonfig_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;fficonfig.h'],['../libidn2_2config_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;config.h'],['../ragel_2config_8h.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'VERSION():&#160;config.h']]],
  ['versioning_2egetting_2dstarted_2emd_870',['versioning.getting-started.md',['../versioning_8getting-started_8md.html',1,'']]],
  ['versioning_2eimplementation_2ddetails_2emd_871',['versioning.implementation-details.md',['../versioning_8implementation-details_8md.html',1,'']]],
  ['versioning_2emd_872',['versioning.md',['../specifications_2versioning_8md.html',1,'(Global Namespace)'],['../users_2versioning_8md.html',1,'(Global Namespace)']]],
  ['versions_5fdb_5fdirectory_873',['VERSIONS_DB_DIRECTORY',['../namespacegenerateBaseline.html#a5437458e3e74922a210b4f7d39e20ef0',1,'generateBaseline.VERSIONS_DB_DIRECTORY()'],['../namespacegeneratePortVersionsDb.html#a54130cc174e3bf89fd87aff1453ceea8',1,'generatePortVersionsDb.VERSIONS_DB_DIRECTORY()']]],
  ['void_5fsighandler_874',['VOID_SIGHANDLER',['../readline-win32_2config_8h.html#ae8a37fa6c27ec6bf124faa70fcd848c5',1,'VOID_SIGHANDLER():&#160;config.h'],['../readline-win32_2config_8h.html#ae8a37fa6c27ec6bf124faa70fcd848c5',1,'VOID_SIGHANDLER():&#160;config.h']]]
];
