var searchData=
[
  ['vcpkg_2019',['Vcpkg',['../md_vcpkg_README_es.html',1,'']]],
  ['vcpkg_20and_20android_2020',['Vcpkg and Android',['../md_vcpkg_docs_users_android.html',1,'']]],
  ['vcpkg_20and_20mingw_2dw64_2021',['Vcpkg and Mingw-w64',['../md_vcpkg_docs_users_mingw.html',1,'']]],
  ['vcpkg_20install_2022',['vcpkg install',['../md_vcpkg_docs_commands_install.html',1,'']]],
  ['vcpkg_20integrate_2023',['vcpkg integrate',['../md_vcpkg_docs_commands_integrate.html',1,'']]],
  ['vcpkg_20pr_20checklist_2024',['Vcpkg PR Checklist',['../md_vcpkg_docs_maintainers_pr_review_checklist.html',1,'']]],
  ['vcpkg_20remove_2025',['vcpkg remove',['../md_vcpkg_docs_commands_remove.html',1,'']]],
  ['vcpkg_20search_2026',['vcpkg search',['../md_vcpkg_docs_commands_search.html',1,'']]],
  ['vcpkg_20telemetry_20and_20privacy_2027',['Vcpkg Telemetry and Privacy',['../md_vcpkg_docs_about_privacy.html',1,'']]],
  ['vcpkg_20x_2dupdate_2dbaseline_2028',['vcpkg x-update-baseline',['../md_vcpkg_docs_commands_update_baseline.html',1,'']]],
  ['vcpkg_2dcmake_2029',['vcpkg-cmake',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_2030',['vcpkg-cmake-config',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_config.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_2031',['vcpkg-cmake-get-vars',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_2032',['vcpkg-get-python-packages',['../md_vcpkg_docs_maintainers_ports_vcpkg_get_python_packages.html',1,'']]],
  ['vcpkg_2dgn_2033',['vcpkg-gn',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_2034',['vcpkg-pkgconfig-get-modules',['../md_vcpkg_docs_maintainers_ports_vcpkg_pkgconfig_get_modules.html',1,'']]],
  ['vcpkg_2dqmake_2035',['vcpkg-qmake',['../md_vcpkg_docs_maintainers_ports_vcpkg_qmake.html',1,'']]],
  ['vcpkg_3a_20export_20android_20prefab_20archives_20_28aar_20files_29_2036',['Vcpkg: export Android prefab Archives (AAR files)',['../md_vcpkg_docs_specifications_prefab.html',1,'']]],
  ['vcpkg_3a_20vue_20d_27ensemble_2037',['Vcpkg: Vue d&apos;ensemble',['../md_vcpkg_README_fr.html',1,'']]],
  ['vcpkg_3a_20总览_2038',['Vcpkg: 总览',['../md_vcpkg_README_zh_CN.html',1,'']]],
  ['vcpkg_3a_20개요_2039',['Vcpkg: 개요',['../md_vcpkg_README_ko_KR.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_2040',['vcpkg_acquire_msys',['../md_vcpkg_docs_maintainers_vcpkg_acquire_msys.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_2041',['vcpkg_add_to_path',['../md_vcpkg_docs_maintainers_vcpkg_add_to_path.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_2042',['vcpkg_apply_patches',['../md_vcpkg_docs_maintainers_vcpkg_apply_patches.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_2043',['vcpkg_backup_restore_env_vars',['../md_vcpkg_docs_maintainers_vcpkg_backup_restore_env_vars.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_2044',['vcpkg_build_cmake',['../md_vcpkg_docs_maintainers_vcpkg_build_cmake.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_2045',['vcpkg_build_make',['../md_vcpkg_docs_maintainers_vcpkg_build_make.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_2046',['vcpkg_build_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_build_msbuild.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_2047',['vcpkg_build_ninja',['../md_vcpkg_docs_maintainers_vcpkg_build_ninja.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_2048',['vcpkg_build_nmake',['../md_vcpkg_docs_maintainers_vcpkg_build_nmake.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_2049',['vcpkg_build_qmake',['../md_vcpkg_docs_maintainers_vcpkg_build_qmake.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_2050',['vcpkg_buildpath_length_warning',['../md_vcpkg_docs_maintainers_vcpkg_buildpath_length_warning.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_2051',['vcpkg_catalog_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_catalog_release_process.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_2052',['vcpkg_check_features',['../md_vcpkg_docs_maintainers_vcpkg_check_features.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_2053',['vcpkg_check_linkage',['../md_vcpkg_docs_maintainers_vcpkg_check_linkage.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_2054',['vcpkg_clean_executables_in_bin',['../md_vcpkg_docs_maintainers_vcpkg_clean_executables_in_bin.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_2055',['vcpkg_clean_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_clean_msbuild.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_2056',['vcpkg_cmake_build',['../md_vcpkg_docs_maintainers_vcpkg_cmake_build.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_2057',['vcpkg_cmake_config_fixup',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_config_vcpkg_cmake_config_fixup.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_2058',['vcpkg_cmake_configure',['../md_vcpkg_docs_maintainers_vcpkg_cmake_configure.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_2059',['vcpkg_cmake_get_vars',['../md_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_2060',['vcpkg_cmake_install',['../md_vcpkg_docs_maintainers_vcpkg_cmake_install.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_2061',['vcpkg_common_definitions',['../md_vcpkg_docs_maintainers_vcpkg_common_definitions.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_2062',['vcpkg_configure_cmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_cmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_2063',['vcpkg_configure_gn',['../md_vcpkg_docs_maintainers_vcpkg_configure_gn.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_2064',['vcpkg_configure_make',['../md_vcpkg_docs_maintainers_vcpkg_configure_make.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_2065',['vcpkg_configure_meson',['../md_vcpkg_docs_maintainers_vcpkg_configure_meson.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_2066',['vcpkg_configure_qmake',['../md_vcpkg_docs_maintainers_vcpkg_configure_qmake.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_2067',['vcpkg_copy_pdbs',['../md_vcpkg_docs_maintainers_vcpkg_copy_pdbs.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_2068',['vcpkg_copy_tool_dependencies',['../md_vcpkg_docs_maintainers_vcpkg_copy_tool_dependencies.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_2069',['vcpkg_copy_tools',['../md_vcpkg_docs_maintainers_vcpkg_copy_tools.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_2070',['vcpkg_download_distfile',['../md_vcpkg_docs_maintainers_vcpkg_download_distfile.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_2071',['vcpkg_execute_build_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_build_process.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_2072',['vcpkg_execute_in_download_mode',['../md_vcpkg_docs_maintainers_vcpkg_execute_in_download_mode.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_2073',['vcpkg_execute_required_process',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_2074',['vcpkg_execute_required_process_repeat',['../md_vcpkg_docs_maintainers_vcpkg_execute_required_process_repeat.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_2075',['vcpkg_extract_source_archive',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_2076',['vcpkg_extract_source_archive_ex',['../md_vcpkg_docs_maintainers_vcpkg_extract_source_archive_ex.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_2077',['vcpkg_fail_port_install',['../md_vcpkg_docs_maintainers_vcpkg_fail_port_install.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_2078',['vcpkg_find_acquire_program',['../md_vcpkg_docs_maintainers_vcpkg_find_acquire_program.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_2079',['vcpkg_find_fortran',['../md_vcpkg_docs_maintainers_vcpkg_find_fortran.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_2080',['vcpkg_fixup_cmake_targets',['../md_vcpkg_docs_maintainers_vcpkg_fixup_cmake_targets.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_2081',['vcpkg_fixup_pkgconfig',['../md_vcpkg_docs_maintainers_vcpkg_fixup_pkgconfig.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_2082',['vcpkg_from_bitbucket',['../md_vcpkg_docs_maintainers_vcpkg_from_bitbucket.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_2083',['vcpkg_from_git',['../md_vcpkg_docs_maintainers_vcpkg_from_git.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_2084',['vcpkg_from_github',['../md_vcpkg_docs_maintainers_vcpkg_from_github.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_2085',['vcpkg_from_gitlab',['../md_vcpkg_docs_maintainers_vcpkg_from_gitlab.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_2086',['vcpkg_from_sourceforge',['../md_vcpkg_docs_maintainers_vcpkg_from_sourceforge.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_2087',['vcpkg_get_program_files_platform_bitness',['../md_vcpkg_docs_maintainers_vcpkg_get_program_files_platform_bitness.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_2088',['vcpkg_get_windows_sdk',['../md_vcpkg_docs_maintainers_vcpkg_get_windows_sdk.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_2089',['vcpkg_gn_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_configure.html',1,'']]],
  ['vcpkg_5fgn_5finstall_2090',['vcpkg_gn_install',['../md_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_install.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_2091',['vcpkg_host_path_list',['../md_vcpkg_docs_maintainers_vcpkg_host_path_list.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_2092',['vcpkg_install_cmake',['../md_vcpkg_docs_maintainers_vcpkg_install_cmake.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_2093',['vcpkg_install_copyright',['../md_vcpkg_docs_maintainers_vcpkg_install_copyright.html',1,'']]],
  ['vcpkg_5finstall_5fgn_2094',['vcpkg_install_gn',['../md_vcpkg_docs_maintainers_vcpkg_install_gn.html',1,'']]],
  ['vcpkg_5finstall_5fmake_2095',['vcpkg_install_make',['../md_vcpkg_docs_maintainers_vcpkg_install_make.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_2096',['vcpkg_install_meson',['../md_vcpkg_docs_maintainers_vcpkg_install_meson.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_2097',['vcpkg_install_msbuild',['../md_vcpkg_docs_maintainers_vcpkg_install_msbuild.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_2098',['vcpkg_install_nmake',['../md_vcpkg_docs_maintainers_vcpkg_install_nmake.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_2099',['vcpkg_install_qmake',['../md_vcpkg_docs_maintainers_vcpkg_install_qmake.html',1,'']]],
  ['vcpkg_5flist_2100',['vcpkg_list',['../md_vcpkg_docs_maintainers_vcpkg_list.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_2101',['vcpkg_minimum_required',['../md_vcpkg_docs_maintainers_vcpkg_minimum_required.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_2102',['vcpkg_qmake_configure',['../md_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_configure.html',1,'']]],
  ['vcpkg_5freplace_5fstring_2103',['vcpkg_replace_string',['../md_vcpkg_docs_maintainers_vcpkg_replace_string.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_2104',['vcpkg_tool_release_process',['../md_vcpkg_docs_maintainers_internal_vcpkg_tool_release_process.html',1,'']]],
  ['versioning_2105',['Versioning',['../md_vcpkg_docs_users_versioning.html',1,'']]],
  ['versioning_20specification_2106',['Versioning Specification',['../md_vcpkg_docs_specifications_versioning.html',1,'']]],
  ['versioning_3a_20implementation_20details_2107',['Versioning: Implementation details',['../md_vcpkg_docs_users_versioning_implementation_details.html',1,'']]]
];
