#ifndef NETWORK_ENUM_HPP
#define NETWORK_ENUM_HPP

namespace Network {

enum Networking { ROOMCREATION, ROOMASKING, ROOMCONNECT, CONNECTED, READY, LAUNCHING, GAMEUPDATE, PLAYERUPDATE, PLAYERDEATH, PLAYERDISCONNECTED, ERROR = -1 };

}

#endif